# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Cpp SMC Sampler Implementation (PET ONLY)
#'
#'
#'IMPORTANT: Recommended that you use \code{smcSamplerRcpp} instead !!
#'IMPORTANT: This function is used for development and unit testing only!!
#'\code{smcSamplerCpp} Returns a List containing various values of the SMC
#'sampler e.g.  particle and (log) weight collection, normalising constant of
#'posterior denisty and other adaptive techniques metadata.
#'
#'This is NOT a general function  like the other samplers, instead this works only
#'for the PET model. However, like \code{smcSampler}, it will provide weighted
#'samples that can be used to approximate different properties of the Bayesian
#'model of interest
#'
#'@param numParticles A number specifiying the number of particles to be used in
#'  the SMC sampler.
#'@param numOfDistributions A number specifiying the number of intermediate
#'  distributions to be used in the simulated annealing (when adpatice CESS is
#'  not used).
#'@param dataset A vector containing the data point.
#'@param timeFrames A vector containing the data point.
#'@param dimParameter The dimension of the paramaters space.
#'
#'@export
smcSamplerCpp <- function(numParticles, numOfDistrubtions, dataSet, timeFrames, dimParameters) {
    .Call(`_bayespetr_smcSamplerCpp`, numParticles, numOfDistrubtions, dataSet, timeFrames, dimParameters)
}

rTakeit <- function(test) {
    invisible(.Call(`_bayespetr_rTakeit`, test))
}

mcmcMoveToy <- function(initialValue, steps, alphaT, data, stepSize, priorSigma, mu, likeSigma) {
    .Call(`_bayespetr_mcmcMoveToy`, initialValue, steps, alphaT, data, stepSize, priorSigma, mu, likeSigma)
}

#'@export
smcSamplerToyCpp <- function(numParticles, numOfDistrubtions, dataSet, dimParameters, priorSigma, likeSigma, mu) {
    .Call(`_bayespetr_smcSamplerToyCpp`, numParticles, numOfDistrubtions, dataSet, dimParameters, priorSigma, likeSigma, mu)
}

rTakeitToy <- function(test) {
    invisible(.Call(`_bayespetr_rTakeitToy`, test))
}

intpolFitValue <- function(timeIndex, phi, theta) {
    .Call(`_bayespetr_intpolFitValue`, timeIndex, phi, theta)
}

set_seed <- function(seed) {
    invisible(.Call(`_bayespetr_set_seed`, seed))
}

#'@export
dataFromR <- function(r_pet_data, config_model) {
    invisible(.Call(`_bayespetr_dataFromR`, r_pet_data, config_model))
}

#'@export
cpp_load_conv_table <- function(pet_conv_dir) {
    invisible(.Call(`_bayespetr_cpp_load_conv_table`, pet_conv_dir))
}

#'@export
vSMCRCppSampler <- function(numSamples, prior5_iter_num, modelNumber, R_config, randSeed) {
    .Call(`_bayespetr_vSMCRCppSampler`, numSamples, prior5_iter_num, modelNumber, R_config, randSeed)
}

